image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test

test:
  stage: test
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
     - pytest -V

setup:
  stage: build
  before_script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
     - python setup.py bdist_wheel
     - pip install dist/*
  artifacts:
    paths:
      - dist/*.whl

docker-build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login --username kstmorozov --password "$DOCKER_TOKEN"
    - docker build -t kstmorozov/goodok-server .
    - docker push kstmorozov/goodok-server:latest
  only:
    - master

#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc ; make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
