repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict

- repo: local

  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=79, --target-version=py37]
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [ python ]
      args: [ --max-complexity=10,
              --ignore-docstrings=yes,
                server ]
#    - id: pylint
#      name: pylint
#      entry: pylint
#      language: system
#      types: [ python ]
#      args: [ --output-format=colorized,
#              --min-similarity-lines=40,
#              --ignore-imports=no,
#              --ignore-comments=yes,
#              --ignore-docstrings=yes,
#              server ]

#    - id: tests
#        name: Run tests
#        entry: "bash tests.sh"
#        language: system
#        verbose: true
